# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'agent1'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/IntelliqDevops/maven.git'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cd /home/azureuser/myagent/_work/1/s;mvn package'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'scp /home/azureuser/myagent/_work/1/s/webapp/target/webapp.war azureuser@4.227.137.182:/var/lib/tomcat10/webapps/mytest.war'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/IntelliqDevops/FunctionalTesting.git'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'java -jar /home/azureuser/myagent/_work/1/s/FunctionalTesting/testing.jar'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'scp /home/azureuser/myagent/_work/1/s/webapp/target/webapp.war azureuser@20.106.20.155:/var/lib/tomcat10/webapps/myprod.war'