# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'agent1'

stages:
  - stage: Download
    jobs:
     - job: DownloadJob
       steps:
        - task:
          inputs:
           targetType: inline
           script: 'git clone https://github.com/IntelliqDevops/maven.git'
